[PinPadCompartilhado]
Porta=COM10
[SiTef]
;PortaSiTef=4096
[PinPad]
MensagemPadrao=Softsystem
[Geral]
;ConfirmarValorPinPad=1
;TransacoesAdicionaisHabilitadas=
;TransacoesHabilitadas=
;TransacoesDesabilitadas=
[Redes]
;HabilitaRedeXXX=1
