/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CONTADORES (
    REG   VARCHAR(4),
    QTDE  INTEGER
);


CREATE TABLE TB_ECFA170 (
    CODIGO   INTEGER,
    LOJA     INTEGER,
    NUMITEM  INTEGER,
    CODITEM  VARCHAR(50),
    TIPO     VARCHAR(1)
);


CREATE TABLE TB_ECFC100 (
    INI            VARCHAR(1),
    REG            VARCHAR(4),
    IND_OPER       INTEGER,
    IND_EMIT       INTEGER,
    COD_PART       VARCHAR(14),
    COD_MOD        VARCHAR(2),
    COD_SIT        VARCHAR(2),
    SER            VARCHAR(3),
    NUM_DOC        VARCHAR(9),
    CHV_NFE        VARCHAR(100),
    DT_DOC         VARCHAR(8),
    DT_E_S         VARCHAR(8),
    VL_DOC         DOUBLE PRECISION,
    IND_PGTO       INTEGER,
    VL_DESC        DOUBLE PRECISION,
    VL_ABAT_NT     DOUBLE PRECISION,
    VL_MERC        DOUBLE PRECISION,
    IND_FRT        INTEGER,
    VL_FRT         DOUBLE PRECISION,
    VL_SEG         DOUBLE PRECISION,
    VL_OUT_DA      DOUBLE PRECISION,
    VL_BC_ICMS     DOUBLE PRECISION,
    VL_ICMS        DOUBLE PRECISION,
    VL_BC_ICMS_ST  DOUBLE PRECISION,
    VL_ICMS_ST     DOUBLE PRECISION,
    VL_IPI         DOUBLE PRECISION,
    VL_PIS         DOUBLE PRECISION,
    VL_COFINS      DOUBLE PRECISION,
    VL_PIS_ST      DOUBLE PRECISION,
    VL_COFINS_ST   DOUBLE PRECISION,
    CODIGO         INTEGER,
    TIPO           VARCHAR(1),
    FIM            VARCHAR(1),
    LOJAP          INTEGER,
    DT1            DATE,
    DT2            DATE
);


CREATE TABLE TB_ECFC100COMPRAS (
    LOJA                      INTEGER,
    CODCOMPRA                 INTEGER,
    STATUS                    INTEGER,
    CNPJ                      VARCHAR(18),
    IE                        VARCHAR(20),
    DATA                      TIMESTAMP,
    UF                        VARCHAR(2),
    MODELO                    VARCHAR(2),
    CHV_NFE                   VARCHAR(100),
    SERIE                     VARCHAR(3),
    SUBSERIE                  VARCHAR(2),
    NUMERO                    VARCHAR(10),
    CFOP                      VARCHAR(4),
    EMITENTE                  VARCHAR(1),
    SITTRIB                   VARCHAR(3),
    SITTRIBIPI                VARCHAR(3),
    SITTRIBPIS                VARCHAR(3),
    SITTRIBCOFINS             VARCHAR(3),
    NUMITEM                   INTEGER,
    CODPRODUTO                INTEGER,
    QUANTIDADE                DOUBLE PRECISION,
    PRECOBRUTO                DOUBLE PRECISION,
    DESCONTO                  DOUBLE PRECISION,
    OUTRASDESPESAS            DOUBLE PRECISION,
    VALORFRETEREAL            DOUBLE PRECISION,
    VALORTOTAL                DOUBLE PRECISION,
    BASEICMS                  DOUBLE PRECISION,
    BASEICMSST                DOUBLE PRECISION,
    VALORICMS                 DOUBLE PRECISION,
    VALORICMSST               DOUBLE PRECISION,
    ISENTAS                   DOUBLE PRECISION,
    OUTRAS                    DOUBLE PRECISION,
    ALIQUOTAICMS              DOUBLE PRECISION,
    ALIQUOTAICMSST            DOUBLE PRECISION,
    ALIQUOTAIPI               DOUBLE PRECISION,
    ALIQUOTAPIS               DOUBLE PRECISION,
    ALIQUOTACOFINS            DOUBLE PRECISION,
    VALORIPI                  DOUBLE PRECISION,
    BASEIPI                   DOUBLE PRECISION,
    BASEPIS                   DOUBLE PRECISION,
    SITUACAO                  VARCHAR(1),
    CODIGONCM                 VARCHAR(30),
    DESCRICAO                 VARCHAR(80),
    CODEMBALAGEM              VARCHAR(3),
    CODANTECIPACAOTRIBUTARIA  VARCHAR(1),
    MODALIDADEFRETE           INTEGER,
    NFSERVICOTRANSPORTE       VARCHAR(1),
    REDUCAOBASEICMS           DOUBLE PRECISION,
    VALORPIS                  DOUBLE PRECISION,
    VALORCOFINS               DOUBLE PRECISION,
    BASECOFINS                DOUBLE PRECISION,
    DATASTATUS                TIMESTAMP,
    BASEICMSSTC195            DOUBLE PRECISION,
    VALORICMSSTC195           DOUBLE PRECISION
);


CREATE TABLE TB_ECFC100VENDAS (
    LOJA             INTEGER,
    CODORCAMENTO     INTEGER,
    STATUS           INTEGER,
    STATUSNFE        INTEGER,
    DATA             TIMESTAMP,
    CNPJ             VARCHAR(14),
    IE               VARCHAR(18),
    UF               VARCHAR(2),
    MODELO           VARCHAR(2),
    CHV_NFE          VARCHAR(100),
    SERIE            VARCHAR(3),
    EMITENTE         VARCHAR(1),
    NUMERO           VARCHAR(20),
    CFOP             VARCHAR(4),
    SITTRIB          VARCHAR(3),
    SITTRIBIPI       VARCHAR(3),
    SITTRIBPIS       VARCHAR(3),
    SITTRIBCOFINS    VARCHAR(3),
    NUMITEM          INTEGER,
    TIPOPRODUTO      VARCHAR(1),
    CODPRODUTO       VARCHAR(50),
    QUANTIDADE       DOUBLE PRECISION,
    PRECOBRUTO       DOUBLE PRECISION,
    DESCONTODESPESA  DOUBLE PRECISION,
    VALORTOTAL       DOUBLE PRECISION,
    BASEICMSST       DOUBLE PRECISION,
    ALIQUOTAICMSST   DOUBLE PRECISION,
    VALORICMSST      DOUBLE PRECISION,
    BASEICMS         DOUBLE PRECISION,
    VALORICMS        DOUBLE PRECISION,
    ISENTAS          DOUBLE PRECISION,
    OUTRAS           DOUBLE PRECISION,
    ALIQUOTAICMS     DOUBLE PRECISION,
    BASEIPI          DOUBLE PRECISION,
    ALIQUOTAIPI      DOUBLE PRECISION,
    VALORIPI         DOUBLE PRECISION,
    BASEPIS          DOUBLE PRECISION,
    ALIQUOTAPIS      DOUBLE PRECISION,
    VALORPIS         DOUBLE PRECISION,
    BASECOFINS       DOUBLE PRECISION,
    ALIQUOTACOFINS   DOUBLE PRECISION,
    VALORCOFINS      DOUBLE PRECISION,
    SITUACAO         VARCHAR(1),
    CODIGONCM        VARCHAR(30),
    DESCRICAO        VARCHAR(80),
    CODEMBALAGEM     VARCHAR(3),
    OUTRASDESPESAS   DOUBLE PRECISION,
    REDUCAOBASEICMS  DOUBLE PRECISION,
    CUPOMFISCAL      INTEGER
);


CREATE TABLE TB_ECFC110 (
    REG      VARCHAR(4),
    COD_INF  INTEGER,
    TXT      VARCHAR(100)
);


CREATE TABLE TB_ECFC120 (
    NUM_DOC  INTEGER
);


CREATE TABLE TB_ECFC140 (
    NUM_DOC  INTEGER
);


CREATE TABLE TB_ECFC141 (
    NUM_DOC  INTEGER
);


CREATE TABLE TB_ECFC170 (
    CODIGO   INTEGER,
    LOJA     INTEGER,
    NUMITEM  INTEGER,
    CODITEM  VARCHAR(50),
    TIPO     VARCHAR(1)
);


CREATE TABLE TB_ECFC190 (
    CODIGO  INTEGER,
    TIPO    VARCHAR(1)
);


CREATE TABLE TB_ECFC195 (
    REG      VARCHAR(4) NOT NULL,
    COD_INF  INTEGER,
    TXT      VARCHAR(100)
);


CREATE TABLE TB_ECFC197 (
    CODAJ           VARCHAR(10),
    DESCR_COMPL_AJ  VARCHAR(50),
    COD_ITEM        INTEGER,
    VL_BC_ICMS      DOUBLE PRECISION,
    ALIQ_ICMS       DOUBLE PRECISION,
    VL_ICMS         DOUBLE PRECISION,
    VL_OUTROS       DOUBLE PRECISION
);


CREATE TABLE TB_ECFC405 (
    REG            VARCHAR(4),
    DT_DOC         VARCHAR(8),
    CRO            INTEGER,
    CRZ            INTEGER,
    NUM_COO_FIN    INTEGER,
    GT_FIN         DOUBLE PRECISION,
    VL_BRT         DOUBLE PRECISION,
    FIM            VARCHAR(1),
    DATA_EMISSAOP  DATE,
    LOJAP          INTEGER,
    SERIALECFP     VARCHAR(20),
    CODECFIDENT    INTEGER
);


CREATE TABLE TB_ECFC420 (
    SERIALECF     VARCHAR(20),
    DATA_EMISSAO  DATE,
    LOJA          INTEGER,
    COD_TOT_PAR   VARCHAR(10),
    VLR_ACUM_TOT  DOUBLE PRECISION,
    NR_TOT        INTEGER,
    DESCR_NR_TOT  VARCHAR(30)
);


CREATE TABLE TB_ECFC460 (
    REG           VARCHAR(4),
    COD_MOD       VARCHAR(2),
    COD_SIT       VARCHAR(3),
    NUM_DOC       INTEGER,
    DT_DOC        VARCHAR(8),
    VL_DOC        DOUBLE PRECISION,
    VL_PIS        DOUBLE PRECISION,
    VL_COFINS     DOUBLE PRECISION,
    CPF_CNPJ      VARCHAR(14),
    NOM_ADQ       VARCHAR(60),
    CODORCAMENTO  INTEGER,
    LOJAP         INTEGER
);


CREATE TABLE TB_ECFC470 (
    REG        VARCHAR(4),
    COD_ITEM   VARCHAR(30),
    QTD        DOUBLE PRECISION,
    QTD_CANC   DOUBLE PRECISION,
    UNID       VARCHAR(6),
    VL_ITEM    DOUBLE PRECISION,
    CST_ICMS   VARCHAR(3),
    CFOP       INTEGER,
    ALIQ_ICMS  DOUBLE PRECISION,
    VL_PIS     DOUBLE PRECISION,
    VL_COFINS  DOUBLE PRECISION
);


CREATE TABLE TB_ECFC481 (
    CST_PIS    VARCHAR(2),
    VL_ITEM    DOUBLE PRECISION,
    VL_BC_PIS  DOUBLE PRECISION,
    ALIQ_PIS   DOUBLE PRECISION,
    VL_PIS     DOUBLE PRECISION,
    COD_ITEM   INTEGER
);


CREATE TABLE TB_ECFC485 (
    CST_COFINS    VARCHAR(2),
    VL_ITEM       DOUBLE PRECISION,
    VL_BC_COFINS  DOUBLE PRECISION,
    ALIQ_COFINS   DOUBLE PRECISION,
    VL_COFINS     DOUBLE PRECISION,
    COD_ITEM      INTEGER
);


CREATE TABLE TB_ECFC490 (
    CST_ICMS    VARCHAR(3),
    CFOP        INTEGER,
    ALIQ_ICMS   DOUBLE PRECISION,
    VL_OPR      DOUBLE PRECISION,
    VL_BC_ICMS  DOUBLE PRECISION,
    VL_ICMS     DOUBLE PRECISION
);


CREATE TABLE TB_ECFC490ECF (
    LOJA          INTEGER,
    CODORCAMENTO  INTEGER,
    STATUS        INTEGER,
    DATA          TIMESTAMP,
    NUMSERIEECF   VARCHAR(30),
    MODELO        VARCHAR(2),
    CUPOMFISCAL   INTEGER,
    NUMITEM       INTEGER,
    CODPRODUTO    VARCHAR(30),
    QUANTIDADE    DOUBLE PRECISION,
    VALORLIQUIDO  DOUBLE PRECISION,
    BASEICMS      DOUBLE PRECISION,
    VALORICMS     DOUBLE PRECISION,
    SITTRIB       VARCHAR(4),
    ALIQ_ICMS     DOUBLE PRECISION,
    CFOP          INTEGER
);


CREATE TABLE TB_ECFC491 (
    CST_PIS    VARCHAR(2),
    CFOP       VARCHAR(4),
    VL_ITEM    DOUBLE PRECISION,
    VL_BC_PIS  DOUBLE PRECISION,
    ALIQ_PIS   DOUBLE PRECISION,
    VL_PIS     DOUBLE PRECISION,
    COD_ITEM   INTEGER
);


CREATE TABLE TB_ECFC495 (
    CST_COFINS    VARCHAR(2),
    CFOP          VARCHAR(4),
    VL_ITEM       DOUBLE PRECISION,
    VL_BC_COFINS  DOUBLE PRECISION,
    ALIQ_COFINS   DOUBLE PRECISION,
    VL_COFINS     DOUBLE PRECISION,
    COD_ITEM      INTEGER
);


CREATE TABLE TB_ECFC49X_ECF (
    LOJA           INTEGER,
    CODORCAMENTO   INTEGER,
    STATUS         INTEGER,
    DATA           TIMESTAMP,
    NUMSERIEECF    VARCHAR(30),
    MODELO         VARCHAR(2),
    CUPOMFISCAL    INTEGER,
    NUMITEM        INTEGER,
    CODPRODUTO     VARCHAR(30),
    QUANTIDADE     DOUBLE PRECISION,
    VALORLIQUIDO   DOUBLE PRECISION,
    CFOP           INTEGER,
    SITTRIBPIS     VARCHAR(2),
    BASEPIS        DOUBLE PRECISION,
    ALIQ_PIS       DOUBLE PRECISION,
    VALORPIS       DOUBLE PRECISION,
    SITTRIBCOFINS  VARCHAR(2),
    BASECOFINS     DOUBLE PRECISION,
    ALIQ_COFINS    DOUBLE PRECISION,
    VALORCOFINS    DOUBLE PRECISION
);


CREATE TABLE TB_ECFD110 (
    REG       VARCHAR(4),
    NUM_ITEM  INTEGER,
    COD_ITEM  INTEGER,
    VL_SERV   DOUBLE PRECISION,
    VL_OUT    DOUBLE PRECISION
);


CREATE TABLE TB_ECFD190 (
    CODIGO  INTEGER,
    TIPO    VARCHAR(1)
);


CREATE TABLE TB_ECFD201 (
    CST_PIS    VARCHAR(2),
    VL_ITEM    DOUBLE PRECISION,
    VL_BC_PIS  DOUBLE PRECISION,
    ALIQ_PIS   DOUBLE PRECISION,
    VL_PIS     DOUBLE PRECISION
);


CREATE TABLE TB_ECFD205 (
    CST_COFINS    VARCHAR(2),
    VL_ITEM       DOUBLE PRECISION,
    VL_BC_COFINS  DOUBLE PRECISION,
    ALIQ_COFINS   DOUBLE PRECISION,
    VL_COFINS     DOUBLE PRECISION
);


CREATE TABLE TB_ECFD590 (
    REG            VARCHAR(4),
    CST_ICMS       VARCHAR(3),
    CFOP           VARCHAR(4),
    ALIQ_ICMS      DOUBLE PRECISION,
    VL_OPER        DOUBLE PRECISION,
    VL_BC_ICMS     DOUBLE PRECISION,
    VL_ICMS        DOUBLE PRECISION,
    VL_BC_ICMS_ST  DOUBLE PRECISION,
    VL_ICMS_ST     DOUBLE PRECISION,
    VL_RED_BC      DOUBLE PRECISION,
    COD_OBS        VARCHAR(3)
);


CREATE TABLE TB_ECFE210 (
    INI                         VARCHAR(1),
    REG                         VARCHAR(4),
    IND_MOV_ST                  INTEGER,
    VL_SLD_CRED_ANT_ST          DOUBLE PRECISION,
    VL_DEVOL_ST                 DOUBLE PRECISION,
    VL_RESSARC_ST               DOUBLE PRECISION,
    VL_OUT_CRED_ST              DOUBLE PRECISION,
    VL_AJ_CREDITOS_ST           DOUBLE PRECISION,
    VL_RETENCAO_ST              DOUBLE PRECISION,
    VL_OUT_DEB_ST               DOUBLE PRECISION,
    VL_AJ_DEBITOS_ST            DOUBLE PRECISION,
    VL_SLD_DEV_ANT_ST           DOUBLE PRECISION,
    VL_DEDUCOES_ST              DOUBLE PRECISION,
    VL_ICMS_RECOL_ST            DOUBLE PRECISION,
    VL_SLD_CRED_ST_TRANSPORTAR  DOUBLE PRECISION,
    DEB_ESP_ST                  DOUBLE PRECISION,
    FIM                         VARCHAR(1),
    LOJAP                       INTEGER
);


CREATE TABLE TB_ECFM410 (
    CST_PIS  VARCHAR(2)
);


CREATE TABLE TB_ECFM810 (
    CST_COFINS  VARCHAR(2)
);




/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX CONTADORES_IDX1 ON CONTADORES (REG);
CREATE INDEX TB_ECFA170_IDX1 ON TB_ECFA170 (CODIGO, LOJA, NUMITEM);
CREATE INDEX IDX_TB_ECFC100_4 ON TB_ECFC100 (COD_PART);
CREATE INDEX TB_ECFC100_IDX1 ON TB_ECFC100 (CODIGO);
CREATE INDEX TB_ECFC100_IDX2 ON TB_ECFC100 (CODIGO, TIPO);
CREATE INDEX IDX_TB_ECFC100COMPRAS_2 ON TB_ECFC100COMPRAS (CODPRODUTO);
CREATE INDEX TB_ECFC100COMPRAS_IDX1 ON TB_ECFC100COMPRAS (CODCOMPRA);
CREATE INDEX TB_ECFC100COMPRAS_IDX2 ON TB_ECFC100COMPRAS (LOJA, NUMERO, MODELO);
CREATE INDEX TB_ECFC100VENDAS_IDX1 ON TB_ECFC100VENDAS (CODPRODUTO);
CREATE INDEX TB_ECFC100VENDAS_IDX2 ON TB_ECFC100VENDAS (CODORCAMENTO);
CREATE INDEX TB_ECFC100VENDAS_IDX3 ON TB_ECFC100VENDAS (CNPJ);
CREATE INDEX TB_ECFC100VENDAS_IDX4 ON TB_ECFC100VENDAS (LOJA, NUMERO, MODELO);
CREATE INDEX TB_ECFC170_IDX1 ON TB_ECFC170 (CODIGO, LOJA, NUMITEM);
CREATE INDEX TB_ECFC190_IDX1 ON TB_ECFC190 (CODIGO, TIPO);
CREATE INDEX TB_ECFD190_IDX1 ON TB_ECFD190 (CODIGO, TIPO);