SET TERM ^ ;

CREATE OR ALTER TRIGGER ATUALIZAESTOQUEDIA_BI FOR ESTOQUE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  INSERT INTO ESTOQUEDIA (LOJA,CODPRODUTO,LOTE,DATA,ESTOQUE)
  VALUES (NEW.LOJA,NEW.CODPRODUTO,NEW.LOTE,CURRENT_TIMESTAMP,0);
  NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
END
^

CREATE OR ALTER TRIGGER ATUALIZAESTOQUEDIA_BU FOR ESTOQUE
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  IF (OLD.DATAATUALIZACAO IS NULL OR CAST(OLD.DATAATUALIZACAO AS DATE) <> CURRENT_DATE) THEN
    INSERT INTO ESTOQUEDIA (LOJA,CODPRODUTO,LOTE,DATA,ESTOQUE)
    VALUES (NEW.LOJA,NEW.CODPRODUTO,NEW.LOTE,CURRENT_TIMESTAMP,OLD.ESTOQUE);
  NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
END
^

SET TERM ; ^