;Colocar somente os retornos em que a situação ficará como REJEITADA, por padrão o tratamento do faultString deixa a nota como ENVIADA.
[SALVADOR]
FSREJEITADA=Error in deserializing body of request message for operation 'EnviarLoteRPS'
[WebIss20]
FSREJEITADA=Certificado não configurado
[GovDigital]
FSREJEITADA=org.apache.xerces.impl.io.MalformedByteSequenceException,Error reading XMLStreamReader
[Saatri]
FSREJEITADA=A autenticação por username não está habilitada para o prestador informado,O cpf ou a senha do usuário estão incorretos,Erro durante a desserializa..o do corpo da mensagem de solicita..o para a opera..o
[ActCon]
FSREJEITADA=Bad Request
[GNota]
FSREJEITADA=Bad Request
[INFISC]
FSREJEITADA=ERRO : cvc-maxLength-valid,ERRO : cvc-pattern-valid,não tem um aspecto válido em relação ao padrão,Invalid byte 1 of 1-byte UTF-8 sequence,ERRO : cvc-complex-type.2.4.a: Foi detectado um conte.do inv.lido come.ando com o elemento,cvc-complex-type.2.4.a: Foi detectado um conte.do inv.lido come.ando com o elemento,cvc-maxLength-valid: O valor,cvc-type.3.1.3: O valor
[Fiorilli]
FSREJEITADA=Fault occurred while processing,org.hibernate.exception.ConstraintViolationException
[GovBR20]
FSREJEITADA=Error in deserializing body of request message for operation 'EnviarLoteRpsSincrono',O elemento .* inv.lido,um elemento invalido
[THEMA]
FSREJEITADA=Invalid UTF-8 start byte
[ABACO]
FSREJEITADA=Invalid byte 1 of 1-byte UTF-8 sequence
[MARINGA]
FSREJEITADA=Invalid XML
[EQUIPLANO]
FSREJEITADA=Número do lote já utilizado,com.ctc.wstx.exc.WstxIOException: Invalid UTF-8 start byte 0x81 (at char #1135, byte #127)
[SIAP]
FSREJEITADA=Invalid byte 2 of 3-byte UTF-8 sequence
[MANAUS]
FSREJEITADA=Invalid byte 1 of 1-byte UTF-8 sequence
[ISSONLINE]
FSREJEITADA=invalid byte 1 of 1-byte UTF-8 sequence
[PUBLICA]
FSREJEITADA=Invalid byte 1 of 1-byte UTF-8 sequence
[WEBISS]
FSREJEITADA=' contém bytes UTF8 inválidos
[SAOJOSEDOSCAMPOS]
FSREJEITADA=Invalid UTF-8 start byte
[PRESCON]
FSREJEITADA=error in msg parsing:
[SIGISS]
FSREJEITADA=error in msg parsing
[LONDRINA]
FSREJEITADA=error in msg parsing:XML error parsing SOAP payload on line
[GINFES]
FSREJEITADA=org.apache.xerces.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.,Problems creating SAAJ object model
[FISCO]
FSREJEITADA=Data de emissao fora da competencia,Contribuinte nao autenticado,Codigo de Servico invalido
[DEISS]
FSREJEITADA=javax.xml.ws.WebServiceException
[ENOTAFISCAL]
FSREJEITADA=The server encountered an internal error that prevented it from fulfilling this request
[BELOHORIZONTE]
FSREJEITADA=Ocorreu um erro Inesperado. (For input string:
[BETHA]
FSREJEITADA=org.apache.xerces.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
[ISSWEB]
FSREJEITADA=Invalid UTF-8 start byte
[SATURNO]
FSREJEITADA=error in msg parsing
[ERECEITA]
FSREJEITADA=error in msg parsing
[JOAOPESSOA]
FSREJEITADA=O parâmetro nomeado (método) informado não existe
[SIGISS20]
FSREJEITADA=Server was unable to process request. ---> There is an error in XML document
[DSF20]
FSREJEITADA=Arquivo enviado com erro na assinatura.
[FGMAISS]
FSREJEITADA=error in msg parsing: XML error parsing SOAP payload on line 1: Invalid character
[SISTEMAS4R]
FSREJEITADA=Caractere inválido na codificação fornecida.